kind: Pod 
apiVersion: v1 
metadata: 
  name: apphub2
  labels: 
    app: apple 
spec: 
  containers: 
    - name: apple-app 
#       image: hashicorp/http-echo:0.2.3
      image: hashicorp/http-echo:latest
      args: 
        - "-text=test bbbsgsdsdfdfs" 
--- 
kind: Service 
apiVersion: v1 
metadata: 
  name: servicappleehub2
spec: 
  selector: 
    app: apple 
  ports: 
    - port: 5678 # Default port for image
