kind: Pod 
apiVersion: v1 
metadata: 
  name: apphub2
  labels: 
    app: apple 
spec: 
  containers: 
    - name: apple-app 
      image: hashicorp/http-echo 
      args: 
        - "-text=test abc123" 
--- 
kind: Service 
apiVersion: v1 
metadata: 
  name: servicappleehub2
spec: 
  selector: 
    app: apple 
  ports: 
    - port: 5678 # Default port for image
